curl -O http://benalman.com/images/simplified/light.gif
curl -O http://benalman.com/images/simplified/dark.gif
curl -O http://benalman.com/images/simplified/topic.gif
curl -O http://benalman.com/images/simplified/long-url.gif
curl -O http://benalman.com/images/simplified/spotlight.gif
curl -O http://benalman.com/images/simplified/spotlighted.gif
curl -O http://benalman.com/images/simplified/star.gif
curl -O http://benalman.com/images/simplified/starred.gif
curl -O http://benalman.com/images/simplified/smiley.gif
curl -O http://benalman.com/grab/e09f87.png
curl -O http://benalman.com/grab/1a2e9a.png
curl -O http://benalman.com/images/projects/jquery-equalizebottoms/125x125winner.png
curl -O http://benalman.com/images/projects/jquery-equalizebottoms/sample.gif
curl -O http://benalman.com/images/bookmarklets/bm-ie6.gif
curl -O http://benalman.com/grab/2184f5.png
curl -O http://benalman.com/grab/4c4fc9.png
curl -O http://benalman.com/grab/75ed58.png
curl -O http://benalman.com/grab/408ebe.png
curl -O http://benalman.com/grab/b7e79c.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/throttle.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/throttle-no_trailing.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/td-func.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/callback.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/callback.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/pause.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/debounce.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/debounce-at_begin.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/td-func.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/callback.png
curl -O http://benalman.com/images/projects/jquery-throttle-debounce/pause.png
curl -O http://benalman.com/code/projects/jquery-bbq/examples/fragment-advanced/ribs.jpg
curl -O http://benalman.com/code/projects/jquery-bbq/examples/fragment-advanced/kebabs.jpg
curl -O http://benalman.com/code/projects/jquery-bbq/examples/fragment-advanced/steak.jpg
curl -O http://benalman.com/code/projects/jquery-bbq/examples/fragment-advanced/burger.jpg
curl -O http://benalman.com/grab/7a969f.png
curl -O http://benalman.com/grab/921c76.png
curl -O http://benalman.com/grab/f52855.png
curl -O http://benalman.com/grab/ed0d7d.png
curl -O http://benalman.com/grab/35e0a6.png
curl -O http://benalman.com/grab/d2dff6.png